# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import library_pb2 as library__pb2


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/library.AuthService/Login',
                request_serializer=library__pb2.LoginRequest.SerializeToString,
                response_deserializer=library__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Register = channel.unary_unary(
                '/library.AuthService/Register',
                request_serializer=library__pb2.RegisterRequest.SerializeToString,
                response_deserializer=library__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.Verify = channel.unary_unary(
                '/library.AuthService/Verify',
                request_serializer=library__pb2.VerifyRequest.SerializeToString,
                response_deserializer=library__pb2.VerifyResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Verify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=library__pb2.LoginRequest.FromString,
                    response_serializer=library__pb2.LoginResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=library__pb2.RegisterRequest.FromString,
                    response_serializer=library__pb2.RegisterResponse.SerializeToString,
            ),
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=library__pb2.VerifyRequest.FromString,
                    response_serializer=library__pb2.VerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.AuthService/Login',
            library__pb2.LoginRequest.SerializeToString,
            library__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.AuthService/Register',
            library__pb2.RegisterRequest.SerializeToString,
            library__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.AuthService/Verify',
            library__pb2.VerifyRequest.SerializeToString,
            library__pb2.VerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SeatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeats = channel.unary_unary(
                '/library.SeatService/GetSeats',
                request_serializer=library__pb2.GetSeatsRequest.SerializeToString,
                response_deserializer=library__pb2.GetSeatsResponse.FromString,
                _registered_method=True)
        self.GetSeat = channel.unary_unary(
                '/library.SeatService/GetSeat',
                request_serializer=library__pb2.GetSeatRequest.SerializeToString,
                response_deserializer=library__pb2.GetSeatResponse.FromString,
                _registered_method=True)
        self.CheckAvailability = channel.unary_unary(
                '/library.SeatService/CheckAvailability',
                request_serializer=library__pb2.CheckAvailabilityRequest.SerializeToString,
                response_deserializer=library__pb2.CheckAvailabilityResponse.FromString,
                _registered_method=True)
        self.GetBranches = channel.unary_unary(
                '/library.SeatService/GetBranches',
                request_serializer=library__pb2.GetBranchesRequest.SerializeToString,
                response_deserializer=library__pb2.GetBranchesResponse.FromString,
                _registered_method=True)


class SeatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSeats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckAvailability(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBranches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeats,
                    request_deserializer=library__pb2.GetSeatsRequest.FromString,
                    response_serializer=library__pb2.GetSeatsResponse.SerializeToString,
            ),
            'GetSeat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeat,
                    request_deserializer=library__pb2.GetSeatRequest.FromString,
                    response_serializer=library__pb2.GetSeatResponse.SerializeToString,
            ),
            'CheckAvailability': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAvailability,
                    request_deserializer=library__pb2.CheckAvailabilityRequest.FromString,
                    response_serializer=library__pb2.CheckAvailabilityResponse.SerializeToString,
            ),
            'GetBranches': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBranches,
                    request_deserializer=library__pb2.GetBranchesRequest.FromString,
                    response_serializer=library__pb2.GetBranchesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.SeatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.SeatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SeatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSeats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.SeatService/GetSeats',
            library__pb2.GetSeatsRequest.SerializeToString,
            library__pb2.GetSeatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.SeatService/GetSeat',
            library__pb2.GetSeatRequest.SerializeToString,
            library__pb2.GetSeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.SeatService/CheckAvailability',
            library__pb2.CheckAvailabilityRequest.SerializeToString,
            library__pb2.CheckAvailabilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBranches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.SeatService/GetBranches',
            library__pb2.GetBranchesRequest.SerializeToString,
            library__pb2.GetBranchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReservationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateReservation = channel.unary_unary(
                '/library.ReservationService/CreateReservation',
                request_serializer=library__pb2.CreateReservationRequest.SerializeToString,
                response_deserializer=library__pb2.CreateReservationResponse.FromString,
                _registered_method=True)
        self.GetReservation = channel.unary_unary(
                '/library.ReservationService/GetReservation',
                request_serializer=library__pb2.GetReservationRequest.SerializeToString,
                response_deserializer=library__pb2.GetReservationResponse.FromString,
                _registered_method=True)
        self.CheckIn = channel.unary_unary(
                '/library.ReservationService/CheckIn',
                request_serializer=library__pb2.CheckInRequest.SerializeToString,
                response_deserializer=library__pb2.CheckInResponse.FromString,
                _registered_method=True)
        self.CancelReservation = channel.unary_unary(
                '/library.ReservationService/CancelReservation',
                request_serializer=library__pb2.CancelReservationRequest.SerializeToString,
                response_deserializer=library__pb2.CancelReservationResponse.FromString,
                _registered_method=True)
        self.GetUserReservations = channel.unary_unary(
                '/library.ReservationService/GetUserReservations',
                request_serializer=library__pb2.GetUserReservationsRequest.SerializeToString,
                response_deserializer=library__pb2.GetUserReservationsResponse.FromString,
                _registered_method=True)


class ReservationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelReservation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserReservations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReservation,
                    request_deserializer=library__pb2.CreateReservationRequest.FromString,
                    response_serializer=library__pb2.CreateReservationResponse.SerializeToString,
            ),
            'GetReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReservation,
                    request_deserializer=library__pb2.GetReservationRequest.FromString,
                    response_serializer=library__pb2.GetReservationResponse.SerializeToString,
            ),
            'CheckIn': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIn,
                    request_deserializer=library__pb2.CheckInRequest.FromString,
                    response_serializer=library__pb2.CheckInResponse.SerializeToString,
            ),
            'CancelReservation': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelReservation,
                    request_deserializer=library__pb2.CancelReservationRequest.FromString,
                    response_serializer=library__pb2.CancelReservationResponse.SerializeToString,
            ),
            'GetUserReservations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserReservations,
                    request_deserializer=library__pb2.GetUserReservationsRequest.FromString,
                    response_serializer=library__pb2.GetUserReservationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.ReservationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.ReservationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReservationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.ReservationService/CreateReservation',
            library__pb2.CreateReservationRequest.SerializeToString,
            library__pb2.CreateReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.ReservationService/GetReservation',
            library__pb2.GetReservationRequest.SerializeToString,
            library__pb2.GetReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.ReservationService/CheckIn',
            library__pb2.CheckInRequest.SerializeToString,
            library__pb2.CheckInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelReservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.ReservationService/CancelReservation',
            library__pb2.CancelReservationRequest.SerializeToString,
            library__pb2.CancelReservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserReservations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.ReservationService/GetUserReservations',
            library__pb2.GetUserReservationsRequest.SerializeToString,
            library__pb2.GetUserReservationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NotifyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddToWaitlist = channel.unary_unary(
                '/library.NotifyService/AddToWaitlist',
                request_serializer=library__pb2.AddToWaitlistRequest.SerializeToString,
                response_deserializer=library__pb2.AddToWaitlistResponse.FromString,
                _registered_method=True)
        self.GetUserWaitlist = channel.unary_unary(
                '/library.NotifyService/GetUserWaitlist',
                request_serializer=library__pb2.GetUserWaitlistRequest.SerializeToString,
                response_deserializer=library__pb2.GetUserWaitlistResponse.FromString,
                _registered_method=True)
        self.RemoveFromWaitlist = channel.unary_unary(
                '/library.NotifyService/RemoveFromWaitlist',
                request_serializer=library__pb2.RemoveFromWaitlistRequest.SerializeToString,
                response_deserializer=library__pb2.RemoveFromWaitlistResponse.FromString,
                _registered_method=True)
        self.NotifyUsers = channel.unary_unary(
                '/library.NotifyService/NotifyUsers',
                request_serializer=library__pb2.NotifyUsersRequest.SerializeToString,
                response_deserializer=library__pb2.NotifyUsersResponse.FromString,
                _registered_method=True)


class NotifyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddToWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromWaitlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddToWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWaitlist,
                    request_deserializer=library__pb2.AddToWaitlistRequest.FromString,
                    response_serializer=library__pb2.AddToWaitlistResponse.SerializeToString,
            ),
            'GetUserWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserWaitlist,
                    request_deserializer=library__pb2.GetUserWaitlistRequest.FromString,
                    response_serializer=library__pb2.GetUserWaitlistResponse.SerializeToString,
            ),
            'RemoveFromWaitlist': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromWaitlist,
                    request_deserializer=library__pb2.RemoveFromWaitlistRequest.FromString,
                    response_serializer=library__pb2.RemoveFromWaitlistResponse.SerializeToString,
            ),
            'NotifyUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyUsers,
                    request_deserializer=library__pb2.NotifyUsersRequest.FromString,
                    response_serializer=library__pb2.NotifyUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.NotifyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.NotifyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotifyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddToWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.NotifyService/AddToWaitlist',
            library__pb2.AddToWaitlistRequest.SerializeToString,
            library__pb2.AddToWaitlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.NotifyService/GetUserWaitlist',
            library__pb2.GetUserWaitlistRequest.SerializeToString,
            library__pb2.GetUserWaitlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromWaitlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.NotifyService/RemoveFromWaitlist',
            library__pb2.RemoveFromWaitlistRequest.SerializeToString,
            library__pb2.RemoveFromWaitlistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.NotifyService/NotifyUsers',
            library__pb2.NotifyUsersRequest.SerializeToString,
            library__pb2.NotifyUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class OperationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOperation = channel.unary_unary(
                '/library.OperationService/SubmitOperation',
                request_serializer=library__pb2.OperationRequest.SerializeToString,
                response_deserializer=library__pb2.OperationResponse.FromString,
                _registered_method=True)


class OperationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOperation,
                    request_deserializer=library__pb2.OperationRequest.FromString,
                    response_serializer=library__pb2.OperationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'library.OperationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('library.OperationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/library.OperationService/SubmitOperation',
            library__pb2.OperationRequest.SerializeToString,
            library__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
